### ISSUE TITLE
文件点击无法浏览器直接打开，都是直接下载，要怎么设置才能实现点击浏览器打开不下载？

### ISSUE THREAD

**Issue by towerstreet** [DirectoryLister/DirectoryLister#1357]
### Directory Lister Version

5.0.0

### PHP Version

8.3

### Web Server

docker

### Describe the Bug

```yaml
services:

  directory-lister:
    image: phlak/directory-lister:latest
    environment:
      REDIS_HOSTNAME: redis
      APP_DEBUG: false
      APP_LANGUAGE: en
      DISPLAY_READMES: true
      READMES_FIRST: false
      ZIP_DOWNLOADS: false
      TIMEZONE: Asia/Shanghai
      SITE_TITLE: DirectoryLister
      HIDE_DOT_FILES: true
      SORT_ORDER: type
    ports:
      - 8585:80
    volumes:
      - /home/towerstreet/Storage/DirectoryLister:/data
    depends_on: [redis]
    restart: unless-stopped
  
  redis:
    image: redis:7.4
    restart: unless-stopped
```
