### ISSUE TITLE
[feature request]  Upload ,randomized paths & wget compatiblity

### ISSUE THREAD

**Issue by tracure1337** [DirectoryLister/DirectoryLister#1367]
Thank you so much for this wonderful piece of software.

I use it to allow humans to to see firmware and distribute it to them. 

To allow the public without leaking any informations to bots I use a randomized path like 

`https://firmware.example.com/Jw9Z6JH0cW`

but when devices  try to downloads it  fails because php modifies the url to become

`https://firmware.example.com/Jw9Z6JH0cW?file=<filename>`

This does work with wget but not when doing 

`wget  https://firmware.example.com/Jw9Z6JH0cW/<filename>`

For this reason I currently use a second flask app that serves the same files on 

`https://firmware.example.com/<filename>`

Now, to make all of this work I have traefik in front of both services like this:

http,https and http-alt are 80 443 and 8080 respective. 
This exists for devices without TLS support  and even when 8080 is  hardcoded. (true story :-) )

```
services:

  firmware:
    restart: unless-stopped
    build: .
    volumes:
      - ./app:/app
      - ./downloads:/downloads
    environment:
      FLASK_ENV: production
    networks:
        firmware:
        traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firmware.rule=Host(`firmware.example.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.firmware.entrypoints=https,http-alt"
      - "traefik.http.routers.firmware.tls.certresolver=letsencrypt"

      - "traefik.http.services.firmware.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.firmware-download.rule=Host(`firmware.example.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.firmware-download.entrypoints=http,http-alt"
      - "traefik.http.routers.firmware-download.priority=20"


      - "traefik.http.services.firmware.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik"

  directory-lister:
    image: phlak/directory-lister:latest
    environment:
      APP_LANGUAGE: en
      DISPLAY_READMES: true
      READMES_FIRST: true
      ZIP_DOWNLOADS: true
      FILES_PATH: /data
      TIMEZONE: Europe/Berlin
    volumes:
      - ./downloads:/data  #sudo chown -R 33:docker to allow apache and firmware to read the files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directory-lister.rule=Host(`firmware.example.com`) && PathPrefix(`/Jw9Z6JH0cW`)"
      #- "traefik.http.routers.directory-lister.rule=Host(`firmware.example.com`) || HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.directory-lister.entrypoints=http,,http-alt,https"
      - "traefik.http.routers.directory-lister.tls.certresolver=letsencrypt"
      - "traefik.http.services.directory-lister.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.strip-Jw9Z6JH0cW.stripPrefix.prefixes=/Jw9Z6JH0cW"
      - "traefik.http.routers.directory-lister.middlewares=strip-Jw9Z6JH0cW"

    networks:
      - firmware
      - traefik

networks:
  firmware:
  traefik:
    external: true
```

Now since the path for humans is randomized I would like to allow them to make uploads of new firmware and edit/replace the README with the latest one. 

If this could be enabled via environment variables this would be amazing.

Regarding the randomized path. it only worked when stripping it again before the request reaches apache since it only works with / , otherwise it will default to /var/html/.

Thank you so much for your consideration!
