### ISSUE TITLE
Update docker image on dockerhub and add docker-compose configuration to run locally

### ISSUE THREAD

**Issue by edisinovcic** [DirectoryLister/DirectoryLister#266]
**Is your feature request related to a problem? Please describe.**

A description of what the problem is. Ex. I'm always frustrated when...

**Describe the solution you'd like**

A description of what you want to happen.

**Describe alternatives you've considered**

A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by PHLAK** [comment]
Thanks for the suggestion. Can you elaborate?

What exactly are you looking to accomplish here, running Directory Lister in Docker?

What's the use case?

What does running from Docker do for you that you can't already do?

**Comment by edisinovcic** [comment]
Yeah, idea is to run it as a standalone service inside of the docker-compose

**Comment by PHLAK** [comment]
What files are you wanting to list? Files on the host or in the container? If host files, would you expose them to the container via a volume?

**Comment by edisinovcic** [comment]
Yeah, the files are inside other container and are created dynamically, and they will be mounted via volume to this container.

**Comment by edisinovcic** [comment]
Can I help somehow with this?

**Comment by PHLAK** [comment]
In order to make a docker image work properly we would need to support the ability to configure a different "base" directory. That is, the code would have to live in one directory (e.g. `/var/www/directory-lister`) and the listed directory would target another directory (e.g. `/some/other/path`). That way we could load the code while building the image and allow mounting a volume to the listed directory path without clobbering the application files.

I did some investigating today and this is not currently possible the way Directory Lister is written. Directory Lister only lists the files and when it comes to accessing (i.e. downloading) those files it passes that over to the web server to handle. This is an issue because the listed files would be in an entirely different directory that the web server would not have access to.

If you (or anyone else) has any ideas on how to solve this (without adding file handling to Directory Lister) I'm open to suggestions. Maybe someday in the future file handling will be in scope but for now it's not something I wish to add. Closing this issue for now.

**Comment by deltabweb** [comment]
I am currently using directory lister with docker swarm and this is what my stack file looks like:

```
directorylister:
    image: directorylister
    environment:
      - APACHE_RUN_USER=#1000
    ports:
      - 96:80
    networks:
      - caddy
    volumes:
      - /srv/mfs/AppData/DirectoryLister:/var/www/html
      - /srv/mfs/DirA:/var/www/html/DirA
      - /srv/mfs/DirB:/var/www/html/DirB
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 500M
```

I have just created empty `DirA` and `DirB` directories in `/srv/mfs/AppData/DirectoryLister` and I am using a bind mount to share the directories I want to share. I am guessing this method could also be used to share volumes from other docker containers.

I don't consider it a good solution, more of a workaround, but just sharing in case it helps.
